export type Choice = { text: string; open: boolean };

export type Question =
  | { id: number; number: number; kind: 'single'; text: string; helpText: string | null; required: boolean; min: number; max: number; choices: Choice[] }
  | { id: number; number: number; kind: 'multiple'; text: string; helpText: string | null; required: boolean; min: number; max: number; choices: Choice[] }
  | { id: number; number: number; kind: 'text'; text: string; helpText: string | null; required: boolean; maxLength: number | null };

export const SURVEY_TITLE = "JsemBlažená.cz - průzkum";

export const INTRO = {
  title: "Platforma JsemBlažená.cz",
  content: "<p style=\"text-align: center;\">Vítej v krátkém dotazníku k chystané platformě JsemBlažená.cz, který je zcela anonymní a není třeba zadávat ani e-mail. Skládá se z 20 jednoduchých otázek. Odpovědi ti nezaberou více než 5 minut.</p><p style=\"text-align: center;\">S dovolením jsem jako formu oslovování zvolila tykání.</p><p style=\"text-align: center;\">Děkuji ti za tvou ochotu zúčastnit se průzkumu.</p><p style=\"text-align: center;\">Nikola Hodovská</p>",
  startButton: "Začínáme",
};

export const THANKS_HEADING = "Děkuji ti za vyplnění dotazníku";

export const THANKS_HTML = "<p style=\"text-align: center;\">Velmi si vážím tvého času.</p><p style=\"text-align: center;\">Jako poděkování, pokud jsi vyplnila e-mail, ti posílám slíbený dárek.</p><p style=\"text-align: center;\">Tvé odpovědi pomohou vytvořit prostor, který bude sloužit nejen tobě, ale i dalším ženám hledajícím lepší orientaci v péči o tělo i duši.</p><p style=\"text-align: center;\">JsemBlaŽená.cz vzniká proto, aby žádná žena nemusela tápat v hledání jen proto, že neví, kde najít tu nejvhodnější  podporu pro své tělo, duši a životní pohodu.</p><p style=\"text-align: center;\"><a href=\"https://lazena.cz/kdo-jsem/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"text-primary underline\">Nikola Hodovská</a></p>";

export const QUESTIONS: Question[] = [
  {
    id: 89752357,
    number: 1,
    kind: "multiple",
    text: "Kde nejčastěji aktivně hledáš odbornici nebo službu týkající se péče o tělo či duši (tzn. kosmetičku, terapeutku, homeopatku, cvičitelku, průvodkyni...)?",
    helpText: "Vyber jednu nebo více odpovědí",
    required: true,
    min: 1,
    max: 7,
    choices: [{ text: "Google", open: false }, { text: "Facebook", open: false }, { text: "Instagram", open: false }, { text: "TikTok", open: false }, { text: "AI - umělá inteligence", open: false }, { text: "doporučení známých", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89805236,
    number: 2,
    kind: "single",
    text: "Daří se ti vždy jednoduše najít přesně tu odbornici, kterou právě potřebuješ?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "ano vždy", open: false }, { text: "většinou ano", open: false }, { text: "někdy ano, někdy ne", open: false }, { text: "většinou ne", open: false }, { text: "skoro vůbec", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89752423,
    number: 3,
    kind: "multiple",
    text: "Co tě většinou zajímá jako první?",
    helpText: "Vyber maximálně 3 odpovědi",
    required: true,
    min: 1,
    max: 3,
    choices: [{ text: "fotografie", open: false }, { text: "cena", open: false }, { text: "reference", open: false }, { text: "osobní příběh", open: false }, { text: "služby", open: false }, { text: "vzdělání", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89752386,
    number: 4,
    kind: "multiple",
    text: "Podle čeho se při výběru odbornice či služby obvykle rozhoduješ?",
    helpText: "Vyber jednu nebo více odpovědí",
    required: true,
    min: 1,
    max: 6,
    choices: [{ text: "podle doporučení", open: false }, { text: "podle referencí", open: false }, { text: "podle sympatií", open: false }, { text: "podle ceny", open: false }, { text: "podle specializace", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89804294,
    number: 5,
    kind: "single",
    text: "Jak důležité jsou pro tebe reference?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "velice důležité", open: false }, { text: "spíš důležité", open: false }, { text: "spíš nedůležité", open: false }, { text: "absolutně nedůležité", open: false }, { text: "nevím", open: false }],
  },
  {
    id: 89753265,
    number: 6,
    kind: "multiple",
    text: "Co tě nejčastěji odradí od objednání?",
    helpText: "Vyber jednu nebo více odpovědí",
    required: true,
    min: 1,
    max: 7,
    choices: [{ text: "málo informací o poskytovaných službách", open: false }, { text: "nedůvěryhodný profil", open: false }, { text: "chybějící ceny", open: false }, { text: "špatná komunikace od odbornice", open: false }, { text: "neaktivní sociální sítě", open: false }, { text: "chybějící rezervační systém", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89753458,
    number: 7,
    kind: "multiple",
    text: "Při výběru odbornice upřednostňuješ spíše:",
    helpText: "Vyber jednu nebo více odpovědí",
    required: true,
    min: 1,
    max: 5,
    choices: [{ text: "odbornice ve svém okolí (do 20 km)", open: false }, { text: "jsi ochotná dojet i dál", open: false }, { text: "online odbornice (videohovor, online konzultace)", open: false }, { text: "kombinaci obojího (lokální i online)", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89804509,
    number: 8,
    kind: "single",
    text: "Nyní si představ online platformu, na které najdeš na jednom místě odbornice na péči o ženské tělo i duši ze svého okolí přesně podle tvého zadání. Jak zajímavá ti taková platforma připadá?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "velice zajímavá", open: false }, { text: "spíše zajímavá", open: false }, { text: "spíš nezajímavá", open: false }, { text: "absolutně nezajímavá", open: false }, { text: "nevím", open: false }],
  },
  {
    id: 89753394,
    number: 9,
    kind: "single",
    text: "S jakou frekvencí si myslíš, že bys ji navštěvovala?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "několikrát měsíčně", open: false }, { text: "1× měsíčně", open: false }, { text: "několikrát ročně", open: false }, { text: "výjimečně", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89753299,
    number: 10,
    kind: "multiple",
    text: "Jaké odbornice bys vyhledávala?",
    helpText: "Vyber jednu nebo více odpovědí",
    required: true,
    min: 1,
    max: 17,
    choices: [{ text: "kosmetičky, PMU aj.", open: false }, { text: "stylistky, vizážistky, makeup-artistky", open: false }, { text: "kadeřnice a headspa", open: false }, { text: "manikérky, pedikérky", open: false }, { text: "masérky, fyzioterapeutky", open: false }, { text: "terapeutky a psychoterapeutky", open: false }, { text: "koučky, mediátorky", open: false }, { text: "výživové a nutriční poradkyně", open: false }, { text: "trenérky, lektorky jógy a jiné cvičitelky", open: false }, { text: "duly nebo porodní asistentky", open: false }, { text: "průvodkyně, šamanky aj.", open: false }, { text: "laktační poradkyně", open: false }, { text: "bylinkářky, zahradnice aj.", open: false }, { text: "organizátorky domácnosti, paní na úklid", open: false }, { text: "paní na hlídání a jiná pomoc s dětmi", open: false }, { text: "rozvodové právničky a ochrana dětí při rozvodu", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89753333,
    number: 11,
    kind: "multiple",
    text: "Jaké informace bys chtěla u odbornice v medailonku najít?",
    helpText: "Vyber maximálně 5 odpovědí",
    required: true,
    min: 1,
    max: 5,
    choices: [{ text: "cena", open: false }, { text: "reference", open: false }, { text: "vzdělání a certifikáty", open: false }, { text: "zkušenosti", open: false }, { text: "osobní příběh", open: false }, { text: "články nebo rozhovory", open: false }, { text: " odkaz na web / rezervační systém", open: false }, { text: "lokalita / online", open: false }, { text: "fotky", open: false }, { text: "poskytované služby", open: false }, { text: "kontakt", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89753527,
    number: 12,
    kind: "single",
    text: "Jakým způsobem bys ráda vyhledávala svou odbornici?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "chci si ji sama vybrat - kliknu na tlačítko „Procházet katalog“ a nastavím si filtry hledání", open: false }, { text: "ocenila bych doporučení na míru podle mých potřeb - kliknu na tlačítko „Nevím koho hledám“ a zodpovím pár otázek z jejichž výsledků mi budou odbornice doporučeny", open: false }, { text: "používala bych obě možnosti podle situace", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89753638,
    number: 13,
    kind: "multiple",
    text: "Které další části by pro tebe byly na platformě JsemBlažená.cz přínosné kromě samotných medailonků odbornic?",
    helpText: "vyber vše, co bys využila",
    required: true,
    min: 1,
    max: 9,
    choices: [{ text: "blog - inspirativní články od odbornic", open: false }, { text: "podcast - příběhy žen a rozhovory s expertkami (audio/ video)", open: false }, { text: "kalendář online akcí a programů (webináře, kurzy, živá vysílání)", open: false }, { text: "kalendář offline akcí (setkání, ženské kruhy, pobyty, workshopy)", open: false }, { text: "e-mailový newsletter s informacemi a novinkami", open: false }, { text: "AI asistentka, která mi doporučí na míru to nejlepší z celého platformy ", open: false }, { text: "Klub Blažených žen v členské sekci (placený) - měsíční hluboký ponor do určitého tématu", open: false }, { text: "wikipedie - přehledný abecední slovník metod, které nabízejí odbornice z katalogu; každou metodu stručně vysvětlí tak, abys rychle pochopila, co obnáší, a zjistila, zda je pro tebe vhodná", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89804348,
    number: 14,
    kind: "single",
    text: "Doporučila bys takovou platformu své nejlepší kamarádce?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "rozhodně ano", open: false }, { text: "spíš ano", open: false }, { text: "nevím", open: false }, { text: "spíš ne", open: false }, { text: "rozhodně ne", open: false }],
  },
  {
    id: 89753414,
    number: 15,
    kind: "single",
    text: "Zvažovala bys i registraci k e-mailovému odběru novinek?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "ano", open: false }, { text: "spíše ano", open: false }, { text: "nevím", open: false }, { text: "spíše ne", open: false }, { text: "ne", open: false }],
  },
  {
    id: 89752132,
    number: 16,
    kind: "single",
    text: "A na závěr pár otázek i o tobě: Prozraď nám prosím kolik je ti let?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "do 24", open: false }, { text: "25–34", open: false }, { text: "35–44", open: false }, { text: "45–54", open: false }, { text: "55+", open: false }],
  },
  {
    id: 89752159,
    number: 17,
    kind: "multiple",
    text: "V jaké životní etapě se nacházíš?",
    helpText: "Vyber jednu nebo více odpovědí",
    required: true,
    min: 1,
    max: 6,
    choices: [{ text: "studentka", open: false }, { text: "zaměstnaná", open: false }, { text: "podnikatelka / OSVČ", open: false }, { text: "na rodičovské", open: false }, { text: "v důchodu", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89752197,
    number: 18,
    kind: "single",
    text: "Jak bys popsala svůj vztah k péči o sebe?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "je pro mě prioritou", open: false }, { text: "snažím se, ale...", open: false }, { text: "často na sebe zapomínám", open: false }, { text: "pečuji spíš o ostatní než o sebe", open: false }, { text: "teprve se to učím", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89752299,
    number: 19,
    kind: "single",
    text: "Jak často si dopřáváš služby péče o tělo a/ nebo duši?",
    helpText: "Vyber jednu odpověď",
    required: true,
    min: 1,
    max: 1,
    choices: [{ text: "1× týdně", open: false }, { text: "1× měsíčně", open: false }, { text: "několikrát ročně", open: false }, { text: "výjimečně", open: false }, { text: "téměř nikdy", open: false }, { text: "jiná (prosím uveď)", open: true }],
  },
  {
    id: 89752345,
    number: 20,
    kind: "single",
    text: "Kolik cca měsíčně investuješ do péče o sebe?",
    helpText: "Vyber jednu odpověď",
    required: false,
    min: 1,
    max: 1,
    choices: [{ text: "0–500 Kč", open: false }, { text: "500–1 000 Kč", open: false }, { text: "1 000–2 000 Kč", open: false }, { text: "2 000–5 000 Kč", open: false }, { text: "více než 5 000 Kč", open: false }],
  },
];
